# Uncomment this line to define a global platform for your project
# platform :ios, "6.0"

target "pashmak-gui" do
	platform :ios, '7.0'
	pod 'AFNetworking', '~> 2.0'
	pod 'OpenCV', '~>2.4.8'
    pod 'ELCImagePickerController', '~> 0.2'
end

target "pashmak-guiTests" do

end

